stages:
  - coverage
  - sonarqube-check

coverage:
  stage: coverage
  image:
    name: "maven:3.6.3-openjdk-11"
  script:
    - mvn compile
    - mvn test
  artifacts:
    paths:
    - target/classes
    - target/test-classes
    - target/site/jacoco/jacoco.xml
    expire_in: 30 mins
  only:
    refs:
      - master

sonarqube-check:
  stage: sonarqube-check
  image:
    name: "sonarsource/sonar-scanner-cli:4.3"
    entrypoint: [""]
  dependencies:
    - coverage
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME -Dsonar.java.binaries=target/classes -Dsonar.java.test.binaries=target/test-classes -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.tests=src/test -Dsonar.sources=src/main
  only:
    refs:
      - master
